COLS = 31
ROWS = 21
TILE = 28
HUD_HEIGHT = 74

SCREEN_WIDTH = COLS * TILE
SCREEN_HEIGHT = ROWS * TILE + HUD_HEIGHT

CRYSTAL_COUNT = 6
FOV_RADIUS = 8
FOV_RAYS = 240

PLAYER_MOVE_DELAY = 0.12
ESCAPE_BLINK_RANGE = 6
ESCAPE_COOLDOWN = 5.0
HUNTER_STUN_AFTER_BLINK = 1.1
# Конфиг

# Базовые игровые настройки

# Конфигурация размеров экрана
